### ISSUE TITLE
Investigate: helm Test Intermittent failure with 'Inapplicable windows'

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2926] opened 2022-09-09 09:51 UTC
**Summary**:

Helm Test Intermittent failure with 'Inapplicable windows' on SettlementCGS Golden Path Test Collections with the following error:

```JSON
{
  "errorInformation": {
    "errorCode": "3100",
    "errorDescription": "Generic validation error - Inapplicable windows 35"
  }
}
```

Example Reports:
- [Report @ 2022-09-06T17h26](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-09-06T17%3A26%3A05.367Z.html#)

**Work-around**:

Re-run the `helm test`.

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**

`helm tests` should consistently pass without the `Inapplicable windows` with SettlementCGS tests passing as expected.

**Steps to Reproduce**
  1. Deploy v14.0.0 Mojaloop Helm Release
  2. Wait for all services to report healthy (i.e. 6-8m)
  3. Execute several `watch -n 300 helm test moja2 --filter "name=moja2-ml-ttk-test-setup,name=moja2-ml-ttk-test-val-gp"`
  4. Monitor test results, and cancel the `watch` command to stop running further tests

**Specifications**
  - Component (if known): Mojaloop GP Tests (run via Helm)
  - Version: v14.0.0
  - Platform: Helm
  - Subsystem: 
  - Type of testing: N/A
  - Bug found/raised by: N/A

**Notes**:

- Severity when opened: Low
- Priority when opened: Low

**Comment by elnyry-sam-k** [comment] 2022-11-14 14:50
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2926?planning-poker) with Zenhub @mdebarros @kleyow @vijayg10 @sri-miriyala

**Comment by kleyow** [comment] 2022-12-02 02:31
Moving to blocked. After hours of testing, I was not able to replicate this issue. 
Issue is to be reopened if failure happens in daily cron job testing.

**Comment by kleyow** [comment] 2022-12-05 02:26
After observing this issue on Sri's branch of https://github.com/mojaloop/testing-toolkit-test-cases/pull/103 
This issue is most likely cased when trying to do a settlement on a window that is in the process of closing but has not finished closing.

The issue is replicable by running the newly added tests without any delay between creating requests for closing and settling the window.

1) A request is sent to close a window.
2) Without sufficient delay a settlement request is sent for that presumed closed window.
3) The window that is not yet in the closed state will throw Inapplicable window error when the settlement request is sent.

A solution would be to add a delay between requests or have some window state checking in the tests somehow.
An improvement for the settlement service would be logging the state of the window at the time of failure.

**Closed** 2022-12-05 18:22 UTC
Labels: oss-core, bug, core-dev-squad
