### ISSUE TITLE
Edgecase on Email notification feature failure in ML AWS

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#623] opened 2019-02-11 06:12 UTC
**Summary**:
Once an FSP updates NDC after the breach, the emails should reset even if it is in the same hour. This is not working as expected.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
1. When the FSP breaches threshold limit % that was set
2. Email notifications needs to be sent 3 times in an hour with 3 mins apart
3. Then the FSP can increase the NDC to allow more transfers further
4. Then the emails should reset even if it is in the same hour.

**Steps to Reproduce**
 1. When the FSP breaches threshold limit % that was set (send a transfer for the amount so that it breaches threshold limit)
2. Email notifications received 3 times in an hour with 3 mins apart
3. After one hour, I sent a transfer but I did not see email triggered for the same NDC breach
3. Then I increased NDC of payerfsp via PUT /limits
4. I sent another transfer that breached new NDC
5. But I did not receive any emails upon breach of new NDC

**Specifications**
  - Component (if known): CEP
  - Version: 5.1.0
  - Platform: ML AWS
  - Subsystem: Mojaloop
  - Type of testing: Functional
  - Bug found/raised by: @sri-miriyala 

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by elnyry** [comment] 2019-02-11 06:53
Need some clarity here, may be we can discuss.

From what I can understand, I see two issues in this one. The primary issue you raised (as per the description) seems to be an _enhancement_ in my opinion and not a bug. It does seem like common sense but we need to understand that this version is sort of an MVP for CEP and email-notifier and this wasn't part of the initial requirements set. However, this will be next in-line.

Other more pressing issues seems to be that we do have a bug here. This is from Step#3 of the Repro Steps. After an hour, the resetting of the email alerts should happen by default (1hr being the configured period).

**Comment by sri-miriyala** [comment] 2019-02-11 17:10
Sam...yes, agree. I took it implied based on reading the requirement. Sure, I am OK with it being an enhancement, but would like to get @RobReeve clarification too.

Based on what @RobReeve clarifies about this requirement, I will either update this or create a new bug for the second point.

Yes, thanks about the last note. Agreed.

**Comment by RobReeve** [comment] 2019-02-11 17:25
@elnyry @sri-miriyala I see this as a new feature to reset the clock once the NDC is updated. However the email repeat because of the breach should have come 1 hour later.

**Comment by elnyry** [comment] 2019-02-11 17:43
Thanks Rob.. 

@sri-miriyala lets use this issue to track the bug if you can confirm that its still an issue with the latest deployment and I'll create an issue for the enhancement separately..

**Comment by sri-miriyala** [comment] 2019-02-11 17:46
sure. Thanks @RobReeve @elnyry

**Comment by elnyry** [comment] 2019-02-13 13:24
Thanks @sri-miriyala for confirming that the 'bug' is fixed, so lets use this issue to track the enhancement.. I've updated the label to reflect that

**Comment by sri-miriyala** [comment] 2019-02-13 13:25
👍
Thanks,
Sri
QA Lead
Modusbox

**Comment by elnyry-sam-k** [comment] 2020-07-15 08:31
@sri-miriyala , @vgenev - is this still relevant?

**Comment by elnyry-sam-k** [comment] 2021-05-13 09:37
closing this as there hasn't been movement / response for quite some time.. If there is a repro, please re-open and add comments as relevant

**Closed by elnyry-sam-k** 2021-05-13 09:37 UTC
Labels: enhancement, oss-core, story
