### ISSUE TITLE
user management.creating role

### ISSUE THREAD

**Issue by PhyuSinMyat8** [mojaloop/project#3643] opened 2023-11-15 08:48 UTC
- After clicking the “Create Role” button, success message appears. 
- But if user leaves that page and go back to Role management page, an error message is shown although I can access that created role.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1RXQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e223f294ec559fd3afb91ad594b0df440b45287d/image.png)

**Comment by pedrosousabarreto** [comment] 2023-12-07 16:04
Could not reproduce this, the latest changes redirect to the role details page after creation, I suspect this was tested at that time.
Issue was fixed by that other change.

**Closed as completed by pedrosousabarreto** 2023-12-07 16:04 UTC
Labels: bug, vNext
