### ISSUE TITLE
Settlement window not assigned for v1.1 'reserved' transfers

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2526] opened 2021-10-01 10:54 UTC
**Summary**:
When a Payee FSP sends a PUT /transfers with transferState = RESERVED, that transfer is not getting a settlement window assigned  (as part of deferred settlement model).

**Context**:
With Mojaloop FSPIOP v1.1 a feature was introduced which Payee FSP's can use to indicate interest in receiving a notification on completion of a transfer on the Switch. This is done by the payee fsp responding with a 'committed' notification once the transfers completes successfully on the Switch

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**
Similar to transfers where Payee FSPs respond with transferState=COMMITTED, transfers with transferState=RESERVED (from Payee FSPs) should have a settlement window assigned (as part of deferred settlement model)

**Steps to Reproduce**
  1. Configure a Mojaloop deployment with FSPIOP v1.1 APIs
  2. Send a transfer where a Payee FSP responds with transferState=RESERVED in PUT /transfers
  3. Observe results - the transfer gets committed with no settlement window assigned

**Specifications**
  - Component (if known): central-ledger
  - Version: v13.0.2 (helm); central-ledger (v13.14.2)
  - Platform: any
  - Subsystem: ML core (fulfil handler)
  - Type of testing: Adopter testing (demonstration)
  - Bug found/raised by: @mdebarros , @sri-miriyala , @elnyry-sam-k (and other team members)

**Notes**:

- Severity when opened: High
- Priority when opened: Critical

**Comment by mdebarros** [comment] 2021-10-01 10:57
Clossing as this is a duplicate of https://github.com/mojaloop/project/issues/2525

**Closed by mdebarros** 2021-10-01 10:57 UTC
Labels: oss-core, bug
