### ISSUE TITLE
2.10 Exception Handling

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#319] opened 2018-06-21 13:35 UTC
**Goal**:
As a developer I would like to _create Exception Handling_ 

**Tasks**:
- [ ] Prepare scripts for handling exceptions

**Acceptance Criteria**:
- [ ] Prepare scripts for handling exceptions

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment] 2018-07-31 14:39
Moving this to product backlog, as Exception Handling is not prioritized for PI-3

**Comment by elnyry** [comment] 2018-09-12 08:17
Duplicate of other exception/error handling stories

**Closed by elnyry** 2018-09-12 08:17 UTC
Labels: Story, needs clarity
