### ISSUE TITLE
Add discussion docs to GitHub TOC

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#1038] opened 2019-10-28 17:05 UTC
## **Goal**:
As a contributor I want to be aware of the discussions taking place so I can learn about new feature development work

**Tasks**:
- Add the following to the TOC -https://github.com/mojaloop/documentation/tree/master/discussions (this can be before the FAQ)

**Acceptance Criteria**:
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] Ensure latest changes are published to https://mojaloop.io/documentation/

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by kjw000** [comment] 2019-10-31 13:00
@mdebarros - let me know if I should assign this to someone else

**Comment by kjw000** [comment] 2019-11-04 13:01
@mdebarros - I added this to the TOC and made some additional documentation changes.  Can we get these updated to Gitbooks sometime this week?

**Comment by mdebarros** [comment] 2019-11-05 14:47
Hi sorry only noticed this story now. Please ping me on slack so we can sync up on this.

**Comment by mdebarros** [comment] 2019-11-05 16:32
Changes released with https://github.com/mojaloop/documentation/releases/tag/v8.4.0

**Comment by mdebarros** [comment] 2019-11-05 16:50
Deployment failed: https://circleci.com/gh/mojaloop/documentation/1122 <-- will have to investigate the cause

**Comment by mdebarros** [comment] 2019-11-05 19:07
Issue resolved. Need to update the version in the package.json. v8.4.0 release and published :D

**Closed by mdebarros** 2019-11-05 19:07 UTC
Labels: Story
