### ISSUE TITLE
ElasticSearch unstable after a period of time

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1962] opened 2021-01-08 08:35 UTC
**Summary**:
ElasticSearch & Kibana become unavailable after an EFK+APM deployment has been running in the Mojaloop OSS Dev environment for an extended period of time (exact time frame is unclear), currently, the environment has been up since 2020-12-18.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
ElasticSearch & Kibana should continue to operate without hindrance.

**Steps to Reproduce**
  1. Deploy v11.x Helm EFK Chart from the Mojaloop Repo
  2. Leave it operational for a period of time
  3. ElasticSearch and Kibana become unresponsive

**Specifications**
  - Component (if known): EFK
  - Version: v11.x
  - Platform: Helm
  - Subsystem:
  - Type of testing: Manual
  - Bug found/raised by: @oderayi @vijayg10 @mdebarros 

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by vijayg10** [comment] 2021-03-01 13:27
With the new version of EFK, we observed the issue with elastic search still exists. @mdebarros found that the issue is because of the persistent storage and we enabled that 3 days ago. So we want to monitor the service for another 5 days and close this issue.

**Comment by elnyry-sam-k** [comment] 2021-03-09 14:59
Closing as EFK looks stable so far.. Please re-open if there's a repro of the issue

**Closed** 2021-03-09 14:59 UTC
Labels: bug, oss-core
