### ISSUE TITLE
Settlement window with Settlement amount "0" is not able to SETTLE

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#936] opened 2019-08-16 14:35 UTC
**Summary**:
IF there are no transfers in a settlement window, the settlement amount shows "0". It stays in PENDING_SETTLEMENT state all the time but not SETTLED even after running Settle settlements step.
**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**
1. Open a new window (close the existing settlement window)
2. Do not run any transfer in the current open window
3. Close the window 
4. Run all settlement steps (prepare, reserve, commit, settle) on the just closed window
5. The window should be able to update with Status SETTLED

**Steps to Reproduce**
1. Open a new window (close the existing settlement window)
2. Do not run any transfer in the current open window
3. Close the window 
4. Run all settlement steps (prepare, reserve, commit, settle) on the just closed window
5. The window left in PENDING_SETTLEMENT state for ever even after running the SETTLE step.

**Specifications**
  - Component (if known): Central Settlements
  - Version:
  - Platform: MAC OS
  - Subsystem: Mojaloop
  - Type of testing: Integration
  - Bug found/raised by: Sri

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by ggrg** [comment] 2019-08-26 09:45
@sri-miriyala, I was unable to reproduce the bug as described above. Please, provide all requests and corresponding responses. I tried two scenarios and both worked as expected:
1. After creating a settlement with a window without transfers, there's no way to do what you claim in step 4, as there are no accounts to specify. The only possible operation is ABORT on a settlement level and it works as expected:
```
Request:
curl -X PUT \
  http://127.0.0.1:3007/v1/settlements/2 \
  -H 'Accept: */*' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Host: 127.0.0.1:3007' \
  -H 'Postman-Token: 952c8bd3-eec1-46f1-bb56-cc14b356c0a5,1d92f4dd-dcc5-4485-a417-95f321f782f8' \
  -H 'User-Agent: PostmanRuntime/7.13.0' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache' \
  -H 'content-length: 77' \
  -d '{
  "state": "ABORTED",
  "reason": "Aborted 1",
  "externalReference": "1"
}'
Response:
{"id":2,"state":"ABORTED","reason":"Aborted 1"}
Get:
{
    "id": 2,
    "state": "ABORTED",
    "reason": "Aborted 1",
    "createdDate": "2019-08-26T06:41:34.000Z",
    "changedDate": "2019-08-26T06:41:43.000Z",
    "settlementWindows": [
        {
            "id": 3,
            "state": "ABORTED",
            "reason": "Aborted 1",
            "createdDate": "2019-08-26T09:35:39.000Z",
            "changedDate": "2019-08-26T06:41:43.000Z"
        }
    ],
    "participants": []
}
```

2. Then I created two transfers, negating the amounts so that the settlement has two accounts to settle with the amount of 0. I was able to push it through:
```
Get:
{
    "id": 1,
    "state": "SETTLED",
    "reason": "All settlement accounts are SETTLED",
    "createdDate": "2019-08-26T06:35:45.000Z",
    "changedDate": "2019-08-26T06:36:45.000Z",
    "settlementWindows": [
        {
            "id": 2,
            "state": "SETTLED",
            "reason": "All window settlement accounts are settled",
            "createdDate": "2019-08-26T09:32:20.000Z",
            "changedDate": "2019-08-26T06:36:45.000Z"
        }
    ],
    "participants": [
        {
            "id": 2,
            "accounts": [
                {
                    "id": 3,
                    "state": "SETTLED",
                    "reason": "test 11",
                    "netSettlementAmount": {
                        "amount": 0,
                        "currency": "USD"
                    }
                }
            ]
        },
        {
            "id": 3,
            "accounts": [
                {
                    "id": 5,
                    "state": "SETTLED",
                    "reason": "test 11",
                    "netSettlementAmount": {
                        "amount": 0,
                        "currency": "USD"
                    }
                }
            ]
        }
    ]
}
```

**Comment by sri-miriyala** [comment] 2019-08-30 19:13
@ggrg  In your scenario 1, yes.. there are no participants to settle but the settlement state also needs to change from PENDING_SETTLEMENT, PSTRANSFERS_RECORDED, PSTRANSFERS_RESERVED, PSTRANSFERS_COMMITTED and finally SETTLED. Since there are no participants, does the state of the settlement goes from PENDING_SETTLEMENT to SETTLED skipping the states between these two?
When I tested the scenario1, I ran all the steps of the settlements (RECORD, RESERVE, COMMIT, SETTLED) even there are no participants in the window to settle, assuming the settlement and settlement window has to go through these states. When I run so, I was not able to see the final state "SETTLED" even after running SETTLE settlement.

**Comment by elnyry** [comment] 2019-09-02 07:51
@wdcmb @MichaelJBRichards adding you to this to hear your thoughts on what expected / acceptable behavior is on Settlements with no transfers..

**Comment by MichaelJBRichards** [comment] 2019-09-02 08:11
This is a problem that exists in the current settlement model, but will be fixed in the proposed changes for multi-currency settlement. In the changed model, settlement windows will not have a state associated with them. Settlement state will instead be associated with records in the **settlementTransferParticipant** table, and these will be created when the settlement window is closed. In the case of a settlement window with no transfers, of course, no such records will be generated.

Then, when the settlement is requested, the system will check to see that there are records in the **settlementTransferParticipant** table for the settlement windows and currency requested in the settlement. If there are none, then the settlement request will report an error; but there will be no records left in the PENDING_SETTLEMENT state.

So my view is that this problem is a temporary one and we should not devote precious resources to fixing it.

**Comment by elnyry** [comment] 2019-09-02 08:30
Great, thanks for your input Michael.

**Comment by sri-miriyala** [comment] 2019-09-03 04:20
Good that it is going to handle in next stages. Thanks for your input @MichaelJBRichards. @elnyry why don't we keep it open in backlog with a note? So that when this fix is available in later version of settlements, I can test this scenario without fail.

**Comment by elnyry** [comment] 2019-09-03 07:48
@sri-miriyala usually I don't mind, but we're trying to clear out / fix as many bugs as possible as we wrap up Phase-3 and have a good release, so I prefer closing.

However, to make sure we cover this case, may be we need a story with a task that indicates this test case needs to be validated after updates to the Settlements implementation (currently v1.0).

**Comment by sri-miriyala** [comment] 2019-09-03 20:29
This scenario is already added to the casa feature tests folder on the postman scripts collection. As this is not included as part of Goldenpath, we do not see any failures regarding this in daily runs. Also, we know that this is left for future implementations. My recommendation is to keep it in backlog and track.

**Closed** 2019-09-22 07:19 UTC
Labels: bug, question
