### ISSUE TITLE
TTK Golden Path tests intermittently fail due to "PAYEE_INVALID_TIMESTAMP" timing issues

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2307] opened 2021-06-23 11:22 UTC
**Summary**:
TTK Golden Path tests intermittently fail due to "PAYEE_INVALID_TIMESTAMP" timing issues.

This is due to the the test-case not waiting for a confirmation that the POST /transfer was processed successfully.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**

Golden Path tests should NOT intermittently fail due to "PAYEE_INVALID_TIMESTAMP" timing issues.

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known): TTK Golen Path Tests
  - Version: v12.1.2 (and previous)
  - Platform: Testing Toolkit
  - Subsystem: Test Cases
  - Type of testing: Manual
  - Bug found/raised by: @mdebarros 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry-sam-k** [comment] 2021-06-23 12:20
duplicate of #2308

**Closed by elnyry-sam-k** 2021-06-23 12:20 UTC
Labels: bug, duplicate
