### ISSUE TITLE
Enhance "common streaming library" for negative use-cases & Integration tests

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#223] opened 2018-04-25 15:06 UTC
**Goal**:
As a developer I would like to Implement negative use-cases & Integration tests on the "common streaming library"

**Tasks**:
- [ ] Add negative use-cases to Unit tests
- [ ] Add Integration tests

**Acceptance Criteria**:
- [ ] Negative use-cases for Unit Tests in the "common streaming library"
- [ ] Integration tests in the "common streaming library"

**Dependencies**:
- [x] #148 
- [ ] #238

**Comment by elnyry** [comment] 2018-06-19 20:54
Duplicate of #195

**Closed by elnyry** 2018-06-19 20:54 UTC
Labels: Groomed, Story
