### ISSUE TITLE
4.6 Design Duplicate Handling Prepare

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#350] opened 2018-06-22 09:11 UTC
**Goal**:
As a developer I would like to _Design Duplicate Handling Prepare_

**Tasks**:
- [ ] Design Duplicate Handling Prepare

**Acceptance Criteria**:
- [ ] Design Duplicate Handling Prepare

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment] 2018-07-05 14:44
Duplicate of #285

**Closed by elnyry** 2018-07-05 14:44 UTC
Labels: Story
