### ISSUE TITLE
Schema validations on POST /quotes giving 500 http code instead of 400

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1023] opened 2019-10-16 15:26 UTC
**Summary**:
Schema validations on POST /quotes giving 500 http code instead of 400

**Severity**:
(Medium)

**Priority**:
(Medium)

**Steps to Reproduce**
Curl:
```
curl -X POST \
  http://dev1-quoting-service.mojaloop.live/quotes \
  -H 'Accept: application/vnd.interoperability.quotes+json;version=1' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 789' \
  -H 'Content-Type: application/vnd.interoperability.quotes+json;version=1.0' \
  -H 'Date: Wed, 16 Oct 2019 12:54:19 GMT' \
  -H 'FSPIOP-Destination: payeefsp' \
  -H 'FSPIOP-SOurce: payerfsp' \
  -H 'Host: dev1-quoting-service.mojaloop.live' \
  -H 'Postman-Token: 0aa84cba-a54f-4bf9-ba2f-0b9f8c9f0318,8000f53e-749a-494b-b69f-f5e57514febc' \
  -H 'User-Agent: PostmanRuntime/7.18.0' \
  -H 'cache-control: no-cache' \
  -d '{
  "quoteId": "5aa55dbc-b512-400d-a5f5-b47a1b0b39bb",
  "transactionId": "5aa55dbc-b512-400d-a5f5-b47a1b0b39bb",
  "payee": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "{{receiverMSISDN}}",
      "fspId": "payeefsp"
    }
  },
  "payer": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "27713803905",
      "fspId": "payerfsp"
    },
    "personalInfo": {
      "complexName": {
        "firstName": "Mats",
        "lastName": "Hagman"
      },
      "dateOfBirth": "1983-10-25"
    }
  },
  "amountType": "SEND",
  "amount": {
    "amount": "2529.382100000046",
    "currency": "USD"
  },
  "transactionType": {
    "scenario": "TRANSFER",
    "initiator": "PAYER",
    "initiatorType": "CONSUMER"
  },
  "note": "hej"
}'
```
Actual Response:
![image](https://user-images.githubusercontent.com/53434415/66933901-9c6d8e00-f031-11e9-84a8-2cbb72ad3da3.png)

**Expected Behavior**
400 with the correct error code. (similar to /transfers); For reference, similar scenario on POST /transfers gives - ```errorCode:"3101", errorDescription:"Malformed syntax - amount"```

**Specifications**
  - Component (if known): central services
  - Version: v8.1.0 Helm (v8.2.2-snapshot of quoting-service)
  - Platform: AWS Dev
  - Subsystem: quoting-service
  - Type of testing: PR validation of Golden path tests
  - Bug found/raised by: @amarmodus @elnyry 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by gibaros** [comment] 2019-10-16 16:14
Cannot reproduce reported bug, works as expected per screenshot.

<img width="1162" alt="Screen Shot 2019-10-16 at 9 14 03 AM" src="https://user-images.githubusercontent.com/5475265/66938070-5f83a600-eff5-11e9-942a-f51f203b41ca.png">

**Comment by gibaros** [comment] 2019-10-22 14:17
Closing issue as confirmed as a non-issue per screenshot.

**Closed by gibaros** 2019-10-22 14:17 UTC
Labels: bug
