### ISSUE TITLE
v14.1.0 - Issue POST Scenarios Callback is missing on TTK Test-Case 

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3029] opened 2022-11-28 12:48 UTC
**Summary**:

Post Scenarios is failing on GP as follows:

![Screenshot 2022-11-28 at 14.42.23.png](https://images.zenhubusercontent.com/5a0d3bc58a75884b9087a3dd/8cf705ee-ec98-47c7-b10d-682caf8af8ac)

![Screenshot 2022-11-28 at 14 42 43](https://user-images.githubusercontent.com/11392873/204282067-4adbc92e-3511-4630-8903-63a642102681.png)

Showing where Web-socket callback is not returning any result for the Payer:

![Screenshot 2022-11-28 at 14.41.02.png](https://images.zenhubusercontent.com/5a0d3bc58a75884b9087a3dd/093f8c3c-ebb6-4d40-bd80-eead43ce1ec3)

TTK Post-Script Log output:

![Screenshot 2022-11-28 at 14.41.44.png](https://images.zenhubusercontent.com/5a0d3bc58a75884b9087a3dd/03de05c3-6408-4b0c-aae3-6e2b7a07b718)

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**

1. Post Scenarios should pass all assertions.

**Steps to Reproduce**
  1. Deploy Mojaloop v14.1.0 with Daily Cronjob enabled
  2. 2-3rd day of Cronjob shows the above failure
  3. Run the `Post Scenarios` Test-Case from GP Test-Collection to reproduce the above issue

**Specifications**
  - Component (if known): Mojaloop Helm Release
  - Version: v14.1.0
  - Platform: Moja1
  - Subsystem: N/A
  - Type of testing: N/A
  - Bug found/raised by: @mdebarros

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by mdebarros** [comment] 2022-11-30 09:50
Unable to re-produce the issue at this time after an environment restart.

**Comment by elnyry-sam-k** [comment] 2023-01-27 14:53
Unable to reproduce so closing for now.

Please re-open this when there's a repro of this issue

**Closed by elnyry-sam-k** 2023-01-27 14:53 UTC
Labels: oss-core, bug, core-dev-squad
