### ISSUE TITLE
issues exceeding 64 character limit in names 

### ISSUE THREAD

**Issue by tdaly61** [mojaloop/project#2375] opened 2021-08-09 03:51 UTC
**Summary**:
mojaloop component names are so long as to exceed helm/k8s naming limits when mojaloop chart is installed

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
Mojaloop component names should be kept far enough below the 64 character maximum so that users deploying from helm will not exceed the 64 character limit.

`Error: Deployment.apps "mojaloop-centralsettlement-handler-deferredsettlement" is invalid: [spec.template.spec.volumes[1].name: Invalid value: "mojaloop-centralsettlement-handler-deferredsettlement-sidecar-vol": must be no more than 63 characters, spec.template.spec.containers[1].volumeMounts[0].name: Not found: "mojaloop-centralsettlement-handler-deferredsettlement-sidecar-vol"]`

**Steps to Reproduce**
 
-  helm upgrade --install --namespace ml-app **mojaloop** mojaloop/mojaloop -f  /vagrant/install/k3d-values-oss-lab-v2.yaml 

  or more simply 
 
- helm upgrade --install --namespace ml-app **mojaloop** mojaloop/mojaloop.

**Specifications**
  - Component (if known):mojaloop helm deploy
  - Version: 13.0.1 
  - Platform: probably all platforms as it is helm/k8s limit , though I am specifically testing on Rancher k3s.
  - Subsystem:
  - Type of testing: 
  - Bug found/raised by: Tom Daly

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry-sam-k** [comment] 2022-11-28 12:47
Closing it as duplicate of #2322 - please reopen if these are not the same

**Closed by elnyry-sam-k** 2022-11-28 12:47 UTC
Labels: bug, infra-bug
