### ISSUE TITLE
Quoting service: time out error

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1168] opened 2020-01-13 12:41 UTC
**Summary**:
Quoting service takes around 20-30 second to respond to request and also
following error was thrown as POST/ Quote. this was seen twice during last 30 days.
Hence GP collection cron job failed.
After redeployment of quoting service GP collection passed.

error thrown:
```
{ code: '2001',
message: 'Internal server error',
name: 'INTERNAL_SERVER_ERROR',
type:
{ regex: '^20[0-9]{2}$',
description: 'Generic Server Error',
httpStatusCode: 500,
name: 'GENERIC_SERVER_ERROR' },
httpStatusCode: 500 },
extensions: undefined,
```
cause:
```
TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full.
```

**Severity**:
Low

**Priority**:
Medium

**Expected Behavior**

**Steps to Reproduce**
  1. Not yet reproduced in consistent behaviour but following has been observed twice. deploy mojaloop system and keep it running for 7-10 days.

**Specifications**
  - Component (if known): central-services
  - Version:v8.7.0
  - Platform: AWS
  - Subsystem: quoting-service
  - Type of testing: functional - postman - GP collection
  - Bug found/raised by: @amarmodus 

**Notes**:

- Severity when opened:
- Priority when opened:

## Pull Request:##
- [x] https://github.com/mojaloop/quoting-service/pull/220

**Comment by amarmodus** [comment] 2020-02-17 14:20
[Quoting_issue_1168_Helm 8.7.0.log](https://github.com/mojaloop/project/files/4214224/Quoting_issue_1168_Helm.8.7.0.log)

**Comment by elnyry** [comment] 2020-04-13 13:56
Couldn't be reproduced so far.. Steven is waiting for a repro on one of the dev environments. Once a repro is seen, we'll resume this.

**Comment by elnyry** [comment] 2020-05-18 14:22
Please re-open if there is a recurrence.. But this was in observation for 3 sprints and it wasn't noticed, so closing it..

**Comment by elnyry** [comment] 2020-05-28 08:44
Thanks @amarmodus .. @oderayi FYI, looks like we have a repro

**Comment by elnyry** [comment] 2020-06-01 19:53
Thanks! - https://github.com/mojaloop/quoting-service/releases/tag/v10.3.2

**Closed by elnyry** 2020-06-01 19:53 UTC
Labels: bug
