### ISSUE TITLE
Cleanup collection with SDK bulk tests is failing

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#3240] opened 2023-03-27 13:55 UTC
**Summary**:
SDK-Bulk Tests are failing on v15-RC1 with the following result:

--------------------FINAL REPORT--------------------

Test Suite:SDK Bulk Tests
Environment:Development
┌───────────────────────────────────────────────────┐
│                      SUMMARY                      │
├───────────────────┬───────────────────────────────┤
│ Total assertions  │ 281                           │
├───────────────────┼───────────────────────────────┤
│ Passed assertions │ 274                           │
├───────────────────┼───────────────────────────────┤
│ Failed assertions │ 7                             │
├───────────────────┼───────────────────────────────┤
│ Total requests    │ 67                            │
├───────────────────┼───────────────────────────────┤
│ Total test cases  │ 26                            │
├───────────────────┼───────────────────────────────┤
│ Passed percentage │ 97.51%                        │
├───────────────────┼───────────────────────────────┤
│ Started time      │ Fri, 03 Mar 2023 10:32:14 GMT │
├───────────────────┼───────────────────────────────┤
│ Completed time    │ 2023-03-03T10:35:07.613Z      │
├───────────────────┼───────────────────────────────┤
│ Runtime duration  │ 172845 ms                     │
└───────────────────┴───────────────────────────────┘
TTK-Assertion-Report-multi-2023-03-03T10:35:07.613Z.html was generated
Find attached report.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

SDK-Bulk Tests should pass.

**Steps to Reproduce**
 1. Deploy v15-RC1 Backends
  2. Deploy v15-RC1 Mojaloop with Bulk, TTK-Simulators, Bulk, and SDK bulk tests enabled
  3. Run `helm test <installation-name>`
  
**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry-sam-k** [comment] 2023-03-27 14:05
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3240?planning-poker) with Zenhub @sri-miriyala @PaulGregoryBaker @mdebarros @kleyow @vijayg10

**Comment by vijayg10** [comment] 2023-05-23 12:36
I couldn't reproduce this error with the helm version v15. It might be fixed in v15 as the reported issue is with v15-rc1. Here is the screenshot of successful test runs on a local mojaloop deployment.

![image](https://github.com/mojaloop/project/assets/33152110/500c9e4e-1bb7-43c2-a192-30b3b33610b6)

**Closed** 2023-05-26 11:25 UTC
Labels: test-bug, oss-core, bug, pi-21
