### ISSUE TITLE
[helm] - Disabling `finance-portal` still creates the finance-portal deployment

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2106] opened 2021-03-09 02:14 UTC
**Summary**:
I'm trying to deploy a simplified `mojaloop/mojaloop` helm chart, but I can't seem to be able to disable the `finance-portal` component.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
Disabling the finance-portal in the values.yaml file should not deploy anything related to the finance portal

**Steps to Reproduce**
  1. `helm install --dry-run  --namespace ml-app mojaloop mojaloop/mojaloop --set finance-portal.enabled=false > /tmp/chart.yaml`
  2. `cat /tmp/chart.yaml | grep finance-portal`
  3. I can clearly see that the deployment for the finance portal is still active:

```
# Source: mojaloop/charts/finance-portal/templates/secrets.yaml
  name: mojaloop-finance-portal
    app.kubernetes.io/name: finance-portal
    helm.sh/chart: finance-portal-11.0.1
# Source: mojaloop/charts/finance-portal/templates/secrets.yaml
  name: mojaloop-finance-portal-certs
    app.kubernetes.io/name: finance-portal
    helm.sh/chart: finance-portal-11.0.1
# Source: mojaloop/charts/finance-portal/templates/configmap-auth-init.yaml
    app.kubernetes.io/name: finance-portal
    helm.sh/chart: finance-portal-11.0.1
# Source: mojaloop/charts/finance-portal/templates/configmap.yaml
  name: mojaloop-finance-portal
    app.kubernetes.io/name: finance-portal
    helm.sh/chart: finance-portal-11.0.1
  SETTLEMENT_MANAGEMENT_ENDPOINT: "http://mojaloop-finance-portal-settlement-management:5000"
# Source: mojaloop/charts/finance-portal/templates/service.yaml
  name: mojaloop-finance-portal
    app.kubernetes.io/name: finance-portal
    helm.sh/chart: finance-portal-11.0.1
      name: http-finance-portal-backend
      name: http-finance-portal-ui
    app.kubernetes.io/name: finance-portal
# Source: mojaloop/charts/finance-portal/templates/deployment.yaml
  name: mojaloop-finance-portal
    app.kubernetes.io/name: finance-portal
    helm.sh/chart: finance-portal-11.0.1
      app.kubernetes.io/name: finance-portal
        app.kubernetes.io/name: finance-portal
        image: "mojaloop/finance-portal-backend-service:v10.5.1"
            name: mojaloop-finance-portal
            name: mojaloop-finance-portal
          - name: mojaloop-finance-portal-secrets-volume
            mountPath: /opt/finance-portal-backend-service/secrets
        image: "mojaloop/finance-portal-ui:v10.4.3"
            name: mojaloop-finance-portal
            name: mojaloop-finance-portal
        - name: mojaloop-finance-portal-secrets-volume
            secretName: mojaloop-finance-portal-certs
# Source: mojaloop/charts/finance-portal/templates/backend-ingress.yaml
  name: mojaloop-finance-portal-backend
    app.kubernetes.io/name: finance-portal
    helm.sh/chart: finance-portal-11.0.1
    - host: finance-portal.local
              serviceName: mojaloop-finance-portal
# Source: mojaloop/charts/finance-portal/templates/frontend-ingress.yaml
  name: mojaloop-finance-portal-frontend
    app.kubernetes.io/name: finance-portal
    helm.sh/chart: finance-portal-11.0.1
    - host: finance-portal.local
              serviceName: mojaloop-finance-portal

```

**Specifications**
  - Component (if known): Helm
  - Version: `v12`, `master`
  - Bug found/raised by: @lewisdaly 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by mdebarros** [comment] 2021-03-26 12:07
@lewisdaly I have reproduced this, and after some investigation, it looks like its a known Helm issue for child charts:

**Comment by lewisdaly** [comment] 2021-03-26 13:27
Thanks for the followup @mdebarros - I wonder why it's not happening when I disable the testing-toolkit charts...

**Comment by mdebarros** [comment] 2021-06-09 08:22
> Thanks for the followup @mdebarros - I wonder why it's not happening when I disable the testing-toolkit charts...

https://github.com/helm/helm/pull/9184 <-- Worth a read.

**Comment by elnyry-sam-k** [comment] 2022-11-23 13:26
@mdebarros - moving this to review based on your comment on the helm release notes PR.. please close it out when ready..

**Closed** 2022-11-28 12:37 UTC
Labels: blocked, oss-core, bug, triaged, infra-bug
