### ISSUE TITLE
Transfers -ve scenarios failing due to an error in Central Ledger

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#1050] opened 2019-11-06 16:27 UTC
**Summary**:
In the new env, the transfers negative tests are failing due to an error in the Central Ledger.

**Severity**:
High
**Priority**:
Critical

**Expected Behavior**

All the tests associated with these scenarios (block transfer, payee abort, payee invalid fulfil etc) should be passing in the new env.
**Steps to Reproduce**
  1.  Run the Block transfer scenario from the Golden_Path 
  2. two tests will fail which the sims not receiving the response
  3. Go to the cental ledger pod and check the logs.

Central Ledger logs:
```
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare-sidecar] 2019-11-06T16:26:32.756Z - info: Received eventMessage:
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare-sidecar] 2019-11-06T16:26:32.756Z - info: Producer.sendMessage::messageProtocol:'{"id":"f4bd665b-ffb3-4b2b-98c7-f5e40d4fcbee","metadata":{"event":{"id":"66b925d0-f310-4878-895d-71095e7223b6","type":"audit","action":"start","createdAt":"2019-11-06T16:26:32.754Z","state":{"status":"success"}},"trace":{"service":"cl_transfer_prepare","traceId":"c558a42dc7eda0ed5da2f6c1562d51f2","spanId":"8342569a3df9c4fc","parentSpanId":"b46075829347d23b","startTimestamp":"2019-11-06T16:26:32.753Z","tags":{"transactionType":"transfer","transactionAction":"prepare","transactionId":"811af75a-3f98-4d13-8865-58c9387685fe","source":"payerfsp","destination":"payeefsp","payerFsp":"payerfsp","payeeFsp":"payeefsp"}}},"type":"application/json","content":{"value":{"from":"payerfsp","to":"payeefsp","id":"811af75a-3f98-4d13-8865-58c9387685fe","content":{"uriParams":{"id":"811af75a-3f98-4d13-8865-58c9387685fe"},"headers":{"x-forwarded-for":"10.25.224.125","content-length":1069,"accept":"application/vnd.interoperability.transfers+json;version=1","content-type":"application/vnd.interoperability.transfers+json;version=1.0","date":"2019-11-06T16:26:32.000Z","fspiop-source":"payerfsp","fspiop-destination":"payeefsp"},"payload":"data:application/vnd.interoperability.transfers+json;version=1.0;base64,ewogICJ0cmFuc2ZlcklkIjogIjgxMWFmNzVhLTNmOTgtNGQxMy04ODY1LTU4YzkzODc2ODVmZSIsCiAgInBheWVyRnNwIjogInBheWVyZnNwIiwKICAicGF5ZWVGc3AiOiAicGF5ZWVmc3AiLAogICJhbW91bnQiOiB7CiAgICAiYW1vdW50IjogIjk4ODgwOS4zNjA4IiwKICAgICJjdXJyZW5jeSI6ICJVU0QiCiAgfSwKICAiZXhwaXJhdGlvbiI6ICIyMDE5LTExLTA2VDE2OjM2OjMyLjQ2MVoiLAogICJpbHBQYWNrZXQiOiAiQVFBQUFBQUFBQURJRUhCeWFYWmhkR1V1Y0dGNVpXVm1jM0NDQWlCN0luUnlZVzV6WVdOMGFXOXVTV1FpT2lJeVpHWTNOelJsTWkxbU1XUmlMVFJtWmpjdFlUUTVOUzB5WkdSa016ZGhaamRqTW1NaUxDSnhkVzkwWlVsa0lqb2lNRE5oTmpBMU5UQXRObVl5WmkwME5UVTJMVGhsTURRdE1EY3dNMlV6T1dJNE4yWm1JaXdpY0dGNVpXVWlPbnNpY0dGeWRIbEpaRWx1Wm04aU9uc2ljR0Z5ZEhsSlpGUjVjR1VpT2lKTlUwbFRSRTRpTENKd1lYSjBlVWxrWlc1MGFXWnBaWElpT2lJeU56Y3hNemd3TXpreE15SXNJbVp6Y0Vsa0lqb2ljR0Y1WldWbWMzQWlmU3dpY0dWeWMyOXVZV3hKYm1adklqcDdJbU52YlhCc1pYaE9ZVzFsSWpwN2ZYMTlMQ0p3WVhsbGNpSTZleUp3WVhKMGVVbGtTVzVtYnlJNmV5SndZWEowZVVsa1ZIbHdaU0k2SWsxVFNWTkVUaUlzSW5CaGNuUjVTV1JsYm5ScFptbGxjaUk2SWpJM056RXpPREF6T1RFeElpd2labk53U1dRaU9pSndZWGxsY21aemNDSjlMQ0p3WlhKemIyNWhiRWx1Wm04aU9uc2lZMjl0Y0d4bGVFNWhiV1VpT250OWZYMHNJbUZ0YjNWdWRDSTZleUpqZFhKeVpXNWplU0k2SWxWVFJDSXNJbUZ0YjNWdWRDSTZJakl3TUNKOUxDSjBjbUZ1YzJGamRHbHZibFI1Y0dVaU9uc2ljMk5sYm1GeWFXOGlPaUpFUlZCUFUwbFVJaXdpYzNWaVUyTmxibUZ5YVc4aU9pSkVSVkJQVTBsVUlpd2lhVzVwZEdsaGRHOXlJam9pVUVGWlJWSWlMQ0pwYm1sMGFXRjBiM0pVZVhCbElqb2lRMDlPVTFWTlJWSWlMQ0p5WldaMWJtUkpibVp2SWpwN2ZYMTkiLAogICJjb25kaXRpb24iOiAiSE9yMjItSDNBZlRESHJTa1BqSnRWUFJkS291dU1rRFhUUjRlamxRYThLcyIKfQ"},"type":"application/json","metadata":{"correlationId":"811af75a-3f98-4d13-8865-58c9387685fe","event":{"type":"prepare","action":"prepare","createdAt":"2019-11-06T16:26:32.742Z","state":{"status":"success","code":0,"description":"action successful"}},"trace":{"startTimestamp":"2019-11-06T16:26:32.724Z","service":"ml_transfer_prepare","traceId":"c558a42dc7eda0ed5da2f6c1562d51f2","spanId":"b46075829347d23b","tags":{"transactionType":"transfer","transactionAction":"prepare","transactionId":"811af75a-3f98-4d13-8865-58c9387685fe","source":"payerfsp","destination":"payeefsp","payerFsp":"payerfsp","payeeFsp":"payeefsp"}},"protocol.createdAt":1573057592742}},"size":2624,"key":null,"topic":"topic-transfer-prepare","offset":282,"partition":0,"timestamp":1573057592742}}'
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare-sidecar] 2019-11-06T16:26:32.757Z - info: Producer::end
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare] 2019-11-06T16:26:32.761Z - info: PrepareHandler::prepare
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare] 2019-11-06T16:26:32.761Z - info: PrepareHandler::prepare::dupCheck
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare] .returning() is not supported by mysql and will not have any effect.
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare] 2019-11-06T16:26:32.774Z - info: PrepareHandler::prepare::validationPassed
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare-sidecar] 2019-11-06T16:26:32.790Z - info: Received eventMessage:
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare] 2019-11-06T16:26:32.774Z - info: PrepareHandler::prepare::validationPassed::saveTransfer
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare] 2019-11-06T16:26:32.787Z - info: PrepareHandler::prepare::validationPassed::saveTransfer::positionTopic1--P5
[backend-centralledger-handler-transfer-position-7ccc779c7brt2ll centralledger-handler-transfer-position-sidecar] 2019-11-06T16:26:32.832Z - info: Received eventMessage:
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare-sidecar] 2019-11-06T16:26:32.792Z - info: Producer.sendMessage::messageProtocol:'{"id":"6c0b93ac-ce5c-46c8-89a9-d41c19b996a4","metadata":{"event":{"id":"1ea726ad-b146-4bd7-afa0-144f99ea407e","type":"audit","action":"egress","createdAt":"2019-11-06T16:26:32.787Z","state":{"status":"success"}},"trace":{"service":"cl_transfer_prepare","traceId":"c558a42dc7eda0ed5da2f6c1562d51f2","spanId":"8342569a3df9c4fc","parentSpanId":"b46075829347d23b","startTimestamp":"2019-11-06T16:26:32.753Z","tags":{"transactionType":"transfer","transactionAction":"prepare","transactionId":"811af75a-3f98-4d13-8865-58c9387685fe","source":"payerfsp","destination":"payeefsp","payerFsp":"payerfsp","payeeFsp":"payeefsp"}}},"type":"application/json","content":{"from":"payerfsp","to":"payeefsp","id":"811af75a-3f98-4d13-8865-58c9387685fe","content":{"uriParams":{"id":"811af75a-3f98-4d13-8865-58c9387685fe"},"headers":{"x-forwarded-for":"10.25.224.125","content-length":1069,"accept":"application/vnd.interoperability.transfers+json;version=1","content-type":"application/vnd.interoperability.transfers+json;version=1.0","date":"2019-11-06T16:26:32.000Z","fspiop-source":"payerfsp","fspiop-destination":"payeefsp"},"payload":"data:application/vnd.interoperability.transfers+json;version=1.0;base64,ewogICJ0cmFuc2ZlcklkIjogIjgxMWFmNzVhLTNmOTgtNGQxMy04ODY1LTU4YzkzODc2ODVmZSIsCiAgInBheWVyRnNwIjogInBheWVyZnNwIiwKICAicGF5ZWVGc3AiOiAicGF5ZWVmc3AiLAogICJhbW91bnQiOiB7CiAgICAiYW1vdW50IjogIjk4ODgwOS4zNjA4IiwKICAgICJjdXJyZW5jeSI6ICJVU0QiCiAgfSwKICAiZXhwaXJhdGlvbiI6ICIyMDE5LTExLTA2VDE2OjM2OjMyLjQ2MVoiLAogICJpbHBQYWNrZXQiOiAiQVFBQUFBQUFBQURJRUhCeWFYWmhkR1V1Y0dGNVpXVm1jM0NDQWlCN0luUnlZVzV6WVdOMGFXOXVTV1FpT2lJeVpHWTNOelJsTWkxbU1XUmlMVFJtWmpjdFlUUTVOUzB5WkdSa016ZGhaamRqTW1NaUxDSnhkVzkwWlVsa0lqb2lNRE5oTmpBMU5UQXRObVl5WmkwME5UVTJMVGhsTURRdE1EY3dNMlV6T1dJNE4yWm1JaXdpY0dGNVpXVWlPbnNpY0dGeWRIbEpaRWx1Wm04aU9uc2ljR0Z5ZEhsSlpGUjVjR1VpT2lKTlUwbFRSRTRpTENKd1lYSjBlVWxrWlc1MGFXWnBaWElpT2lJeU56Y3hNemd3TXpreE15SXNJbVp6Y0Vsa0lqb2ljR0Y1WldWbWMzQWlmU3dpY0dWeWMyOXVZV3hKYm1adklqcDdJbU52YlhCc1pYaE9ZVzFsSWpwN2ZYMTlMQ0p3WVhsbGNpSTZleUp3WVhKMGVVbGtTVzVtYnlJNmV5SndZWEowZVVsa1ZIbHdaU0k2SWsxVFNWTkVUaUlzSW5CaGNuUjVTV1JsYm5ScFptbGxjaUk2SWpJM056RXpPREF6T1RFeElpd2labk53U1dRaU9pSndZWGxsY21aemNDSjlMQ0p3WlhKemIyNWhiRWx1Wm04aU9uc2lZMjl0Y0d4bGVFNWhiV1VpT250OWZYMHNJbUZ0YjNWdWRDSTZleUpqZFhKeVpXNWplU0k2SWxWVFJDSXNJbUZ0YjNWdWRDSTZJakl3TUNKOUxDSjBjbUZ1YzJGamRHbHZibFI1Y0dVaU9uc2ljMk5sYm1GeWFXOGlPaUpFUlZCUFUwbFVJaXdpYzNWaVUyTmxibUZ5YVc4aU9pSkVSVkJQVTBsVUlpd2lhVzVwZEdsaGRHOXlJam9pVUVGWlJWSWlMQ0pwYm1sMGFXRjBiM0pVZVhCbElqb2lRMDlPVTFWTlJWSWlMQ0p5WldaMWJtUkpibVp2SWpwN2ZYMTkiLAogICJjb25kaXRpb24iOiAiSE9yMjItSDNBZlRESHJTa1BqSnRWUFJkS291dU1rRFhUUjRlamxRYThLcyIKfQ"},"type":"application/json","metadata":{"correlationId":"811af75a-3f98-4d13-8865-58c9387685fe","event":{"type":"position","action":"prepare","createdAt":"2019-11-06T16:26:32.742Z","state":{"status":"success","code":0,"description":"action successful"},"id":"f3c8292c-ff7c-42ed-9a4c-d4258a4f2bc3"},"trace":{"startTimestamp":"2019-11-06T16:26:32.753Z","service":"cl_transfer_prepare","traceId":"c558a42dc7eda0ed5da2f6c1562d51f2","spanId":"8342569a3df9c4fc","parentSpanId":"b46075829347d23b","tags":{"transactionType":"transfer","transactionAction":"prepare","transactionId":"811af75a-3f98-4d13-8865-58c9387685fe","source":"payerfsp","destination":"payeefsp","payerFsp":"payerfsp","payeeFsp":"payeefsp"}},"protocol.createdAt":1573057592742}}}'
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare] 2019-11-06T16:26:32.788Z - info: Producer.sendMessage::messageProtocol:'{"from":"payerfsp","to":"payeefsp","id":"811af75a-3f98-4d13-8865-58c9387685fe","content":{"uriParams":{"id":"811af75a-3f98-4d13-8865-58c9387685fe"},"headers":{"x-forwarded-for":"10.25.224.125","content-length":1069,"accept":"application/vnd.interoperability.transfers+json;version=1","content-type":"application/vnd.interoperability.transfers+json;version=1.0","date":"2019-11-06T16:26:32.000Z","fspiop-source":"payerfsp","fspiop-destination":"payeefsp"},"payload":"data:application/vnd.interoperability.transfers+json;version=1.0;base64,ewogICJ0cmFuc2ZlcklkIjogIjgxMWFmNzVhLTNmOTgtNGQxMy04ODY1LTU4YzkzODc2ODVmZSIsCiAgInBheWVyRnNwIjogInBheWVyZnNwIiwKICAicGF5ZWVGc3AiOiAicGF5ZWVmc3AiLAogICJhbW91bnQiOiB7CiAgICAiYW1vdW50IjogIjk4ODgwOS4zNjA4IiwKICAgICJjdXJyZW5jeSI6ICJVU0QiCiAgfSwKICAiZXhwaXJhdGlvbiI6ICIyMDE5LTExLTA2VDE2OjM2OjMyLjQ2MVoiLAogICJpbHBQYWNrZXQiOiAiQVFBQUFBQUFBQURJRUhCeWFYWmhkR1V1Y0dGNVpXVm1jM0NDQWlCN0luUnlZVzV6WVdOMGFXOXVTV1FpT2lJeVpHWTNOelJsTWkxbU1XUmlMVFJtWmpjdFlUUTVOUzB5WkdSa016ZGhaamRqTW1NaUxDSnhkVzkwWlVsa0lqb2lNRE5oTmpBMU5UQXRObVl5WmkwME5UVTJMVGhsTURRdE1EY3dNMlV6T1dJNE4yWm1JaXdpY0dGNVpXVWlPbnNpY0dGeWRIbEpaRWx1Wm04aU9uc2ljR0Z5ZEhsSlpGUjVjR1VpT2lKTlUwbFRSRTRpTENKd1lYSjBlVWxrWlc1MGFXWnBaWElpT2lJeU56Y3hNemd3TXpreE15SXNJbVp6Y0Vsa0lqb2ljR0Y1WldWbWMzQWlmU3dpY0dWeWMyOXVZV3hKYm1adklqcDdJbU52YlhCc1pYaE9ZVzFsSWpwN2ZYMTlMQ0p3WVhsbGNpSTZleUp3WVhKMGVVbGtTVzVtYnlJNmV5SndZWEowZVVsa1ZIbHdaU0k2SWsxVFNWTkVUaUlzSW5CaGNuUjVTV1JsYm5ScFptbGxjaUk2SWpJM056RXpPREF6T1RFeElpd2labk53U1dRaU9pSndZWGxsY21aemNDSjlMQ0p3WlhKemIyNWhiRWx1Wm04aU9uc2lZMjl0Y0d4bGVFNWhiV1VpT250OWZYMHNJbUZ0YjNWdWRDSTZleUpqZFhKeVpXNWplU0k2SWxWVFJDSXNJbUZ0YjNWdWRDSTZJakl3TUNKOUxDSjBjbUZ1YzJGamRHbHZibFI1Y0dVaU9uc2ljMk5sYm1GeWFXOGlPaUpFUlZCUFUwbFVJaXdpYzNWaVUyTmxibUZ5YVc4aU9pSkVSVkJQVTBsVUlpd2lhVzVwZEdsaGRHOXlJam9pVUVGWlJWSWlMQ0pwYm1sMGFXRjBiM0pVZVhCbElqb2lRMDlPVTFWTlJWSWlMQ0p5WldaMWJtUkpibVp2SWpwN2ZYMTkiLAogICJjb25kaXRpb24iOiAiSE9yMjItSDNBZlRESHJTa1BqSnRWUFJkS291dU1rRFhUUjRlamxRYThLcyIKfQ"},"type":"application/json","metadata":{"correlationId":"811af75a-3f98-4d13-8865-58c9387685fe","event":{"type":"position","action":"prepare","createdAt":"2019-11-06T16:26:32.742Z","state":{"status":"success","code":0,"description":"action successful"},"id":"f3c8292c-ff7c-42ed-9a4c-d4258a4f2bc3"},"trace":{"startTimestamp":"2019-11-06T16:26:32.753Z","service":"cl_transfer_prepare","traceId":"c558a42dc7eda0ed5da2f6c1562d51f2","spanId":"8342569a3df9c4fc","parentSpanId":"b46075829347d23b","tags":{"transactionType":"transfer","transactionAction":"prepare","transactionId":"811af75a-3f98-4d13-8865-58c9387685fe","source":"payerfsp","destination":"payeefsp","payerFsp":"payerfsp","payeeFsp":"payeefsp"}},"protocol.createdAt":1573057592742}}'
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare-sidecar] 2019-11-06T16:26:32.794Z - info: Producer::end
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare] 2019-11-06T16:26:32.788Z - info: Producer::end
[backend-centralledger-handler-transfer-position-7ccc779c7brt2ll centralledger-handler-transfer-position] 2019-11-06T16:26:32.836Z - info: PositionHandler::positions
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare-sidecar] 2019-11-06T16:26:32.795Z - info: Received eventMessage:
[backend-centralledger-handler-transfer-position-7ccc779c7brt2ll centralledger-handler-transfer-position-sidecar] 2019-11-06T16:26:32.832Z - info: Producer.sendMessage::messageProtocol:'{"id":"88a86bf2-36a8-4113-af8c-fb156e4b9c20","metadata":{"event":{"id":"417decf1-4591-483d-b86e-ae020fde3b71","type":"audit","action":"start","createdAt":"2019-11-06T16:26:32.830Z","state":{"status":"success"}},"trace":{"service":"cl_transfer_position","traceId":"c558a42dc7eda0ed5da2f6c1562d51f2","spanId":"d44ddce887144dfe","parentSpanId":"8342569a3df9c4fc","startTimestamp":"2019-11-06T16:26:32.830Z","tags":{"transactionType":"transfer","transactionAction":"prepare","transactionId":"811af75a-3f98-4d13-8865-58c9387685fe","source":"payerfsp","destination":"payeefsp","payerFsp":"payerfsp","payeeFsp":"payeefsp"}}},"type":"application/json","content":{"value":{"from":"payerfsp","to":"payeefsp","id":"811af75a-3f98-4d13-8865-58c9387685fe","content":{"uriParams":{"id":"811af75a-3f98-4d13-8865-58c9387685fe"},"headers":{"x-forwarded-for":"10.25.224.125","content-length":1069,"accept":"application/vnd.interoperability.transfers+json;version=1","content-type":"application/vnd.interoperability.transfers+json;version=1.0","date":"2019-11-06T16:26:32.000Z","fspiop-source":"payerfsp","fspiop-destination":"payeefsp"},"payload":"data:application/vnd.interoperability.transfers+json;version=1.0;base64,ewogICJ0cmFuc2ZlcklkIjogIjgxMWFmNzVhLTNmOTgtNGQxMy04ODY1LTU4YzkzODc2ODVmZSIsCiAgInBheWVyRnNwIjogInBheWVyZnNwIiwKICAicGF5ZWVGc3AiOiAicGF5ZWVmc3AiLAogICJhbW91bnQiOiB7CiAgICAiYW1vdW50IjogIjk4ODgwOS4zNjA4IiwKICAgICJjdXJyZW5jeSI6ICJVU0QiCiAgfSwKICAiZXhwaXJhdGlvbiI6ICIyMDE5LTExLTA2VDE2OjM2OjMyLjQ2MVoiLAogICJpbHBQYWNrZXQiOiAiQVFBQUFBQUFBQURJRUhCeWFYWmhkR1V1Y0dGNVpXVm1jM0NDQWlCN0luUnlZVzV6WVdOMGFXOXVTV1FpT2lJeVpHWTNOelJsTWkxbU1XUmlMVFJtWmpjdFlUUTVOUzB5WkdSa016ZGhaamRqTW1NaUxDSnhkVzkwWlVsa0lqb2lNRE5oTmpBMU5UQXRObVl5WmkwME5UVTJMVGhsTURRdE1EY3dNMlV6T1dJNE4yWm1JaXdpY0dGNVpXVWlPbnNpY0dGeWRIbEpaRWx1Wm04aU9uc2ljR0Z5ZEhsSlpGUjVjR1VpT2lKTlUwbFRSRTRpTENKd1lYSjBlVWxrWlc1MGFXWnBaWElpT2lJeU56Y3hNemd3TXpreE15SXNJbVp6Y0Vsa0lqb2ljR0Y1WldWbWMzQWlmU3dpY0dWeWMyOXVZV3hKYm1adklqcDdJbU52YlhCc1pYaE9ZVzFsSWpwN2ZYMTlMQ0p3WVhsbGNpSTZleUp3WVhKMGVVbGtTVzVtYnlJNmV5SndZWEowZVVsa1ZIbHdaU0k2SWsxVFNWTkVUaUlzSW5CaGNuUjVTV1JsYm5ScFptbGxjaUk2SWpJM056RXpPREF6T1RFeElpd2labk53U1dRaU9pSndZWGxsY21aemNDSjlMQ0p3WlhKemIyNWhiRWx1Wm04aU9uc2lZMjl0Y0d4bGVFNWhiV1VpT250OWZYMHNJbUZ0YjNWdWRDSTZleUpqZFhKeVpXNWplU0k2SWxWVFJDSXNJbUZ0YjNWdWRDSTZJakl3TUNKOUxDSjBjbUZ1YzJGamRHbHZibFI1Y0dVaU9uc2ljMk5sYm1GeWFXOGlPaUpFUlZCUFUwbFVJaXdpYzNWaVUyTmxibUZ5YVc4aU9pSkVSVkJQVTBsVUlpd2lhVzVwZEdsaGRHOXlJam9pVUVGWlJWSWlMQ0pwYm1sMGFXRjBiM0pVZVhCbElqb2lRMDlPVTFWTlJWSWlMQ0p5WldaMWJtUkpibVp2SWpwN2ZYMTkiLAogICJjb25kaXRpb24iOiAiSE9yMjItSDNBZlRESHJTa1BqSnRWUFJkS291dU1rRFhUUjRlamxRYThLcyIKfQ"},"type":"application/json","metadata":{"correlationId":"811af75a-3f98-4d13-8865-58c9387685fe","event":{"type":"position","action":"prepare","createdAt":"2019-11-06T16:26:32.742Z","state":{"status":"success","code":0,"description":"action successful"},"id":"f3c8292c-ff7c-42ed-9a4c-d4258a4f2bc3"},"trace":{"startTimestamp":"2019-11-06T16:26:32.753Z","service":"cl_transfer_prepare","traceId":"c558a42dc7eda0ed5da2f6c1562d51f2","spanId":"8342569a3df9c4fc","parentSpanId":"b46075829347d23b","tags":{"transactionType":"transfer","transactionAction":"prepare","transactionId":"811af75a-3f98-4d13-8865-58c9387685fe","source":"payerfsp","destination":"payeefsp","payerFsp":"payerfsp","payeeFsp":"payeefsp"}},"protocol.createdAt":1573057592788}},"size":2703,"key":{"type":"Buffer","data":[112,97,121,101,101,102,115,112]},"topic":"topic-transfer-position","offset":512,"partition":0,"timestamp":1573057592788}}'
[backend-centralledger-handler-transfer-position-7ccc779c7brt2ll centralledger-handler-transfer-position] 2019-11-06T16:26:32.836Z - info: PositionHandler::positions::prepare
[backend-centralledger-handler-transfer-position-7ccc779c7brt2ll centralledger-handler-transfer-position-sidecar] 2019-11-06T16:26:32.833Z - info: Producer::end
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare-sidecar] 2019-11-06T16:26:32.795Z - info: Producer.sendMessage::messageProtocol:'{"id":"8e42f6ff-77e9-49f8-895c-d94a7d076a86","metadata":{"event":{"id":"fa62b5e0-ff78-4f49-9e9a-56b85e80bd0f","type":"trace","action":"span","createdAt":"2019-11-06T16:26:32.788Z","state":{"status":"success"}},"trace":{"service":"cl_transfer_prepare","traceId":"c558a42dc7eda0ed5da2f6c1562d51f2","spanId":"8342569a3df9c4fc","parentSpanId":"b46075829347d23b","startTimestamp":"2019-11-06T16:26:32.753Z","finishTimestamp":"2019-11-06T16:26:32.788Z","tags":{"transactionType":"transfer","transactionAction":"prepare","transactionId":"811af75a-3f98-4d13-8865-58c9387685fe","source":"payerfsp","destination":"payeefsp","payerFsp":"payerfsp","payeeFsp":"payeefsp"}}},"type":"application/json","content":{"type":"application/json","id":"2db85a77-6c47-42d1-8845-0ab49269fddb","content":{"startTimestamp":"2019-11-06T16:26:32.753Z","service":"cl_transfer_prepare","traceId":"c558a42dc7eda0ed5da2f6c1562d51f2","spanId":"8342569a3df9c4fc","parentSpanId":"b46075829347d23b","tags":{"transactionType":"transfer","transactionAction":"prepare","transactionId":"811af75a-3f98-4d13-8865-58c9387685fe","source":"payerfsp","destination":"payeefsp","payerFsp":"payerfsp","payeeFsp":"payeefsp"},"finishTimestamp":"2019-11-06T16:26:32.788Z"}}}'
[backend-centralledger-handler-transfer-position-7ccc779c7brt2ll centralledger-handler-transfer-position] Connection Error: Error: Connection lost: The server closed the connection.
[backend-centralledger-handler-transfer-position-7ccc779c7brt2ll centralledger-handler-transfer-position-sidecar] 2019-11-06T16:26:32.864Z - info: Received eventMessage:
[backend-centralledger-handler-transfer-prepare-74cfb7dccb-tj98w centralledger-handler-transfer-prepare-sidecar] 2019-11-06T16:26:32.796Z - info: Producer::end
[backend-centralledger-handler-transfer-position-7ccc779c7brt2ll centralledger-handler-transfer-position] 2019-11-06T16:26:32.858Z - info: PositionHandler::positions::prepare::payerNotifyInsufficientLiquidity--P2
[backend-centralledger-handler-transfer-position-7ccc779c7brt2ll centralledger-handler-transfer-position] 2019-11-06T16:26:32.861Z - error: PositionHandler::positions::prepare::payerNotifyInsufficientLiquidity--P2::Cannot read property 'insert' of undefined--0
[backend-centralledger-handler-transfer-position-7ccc779c7brt2ll centralledger-handler-transfer-position-sidecar] 2019-11-06T16:26:32.864Z - info: Producer.sendMessage::messageProtocol:'{"id":"3d179159-4e04-4bb7-b1c8-8bccb599163d","metadata":{"event":{"id":"9837b18d-a9c4-475b-998b-648e2acf0af7","type":"log","action":"error","createdAt":"2019-11-06T16:26:32.861Z","state":{"status":"failed","code":2001,"description":"Internal server error"}},"trace":{"service":"cl_transfer_position","traceId":"c558a42dc7eda0ed5da2f6c1562d51f2","spanId":"d44ddce887144dfe","parentSpanId":"8342569a3df9c4fc","startTimestamp":"2019-11-06T16:26:32.830Z","tags":{"transactionType":"transfer","transactionAction":"prepare","transactionId":"811af75a-3f98-4d13-8865-58c9387685fe","source":"payerfsp","destination":"payeefsp","payerFsp":"payerfsp","payeeFsp":"payeefsp"}}},"type":"application/json","content":{"error":{"name":"FSPIOPError","cause":"TypeError: Cannot read property 'insert' of undefinedn    at Object.insert (/opt/central-ledger/src/models/transfer/transferError.js:52:29)n    at Object.logTransferError (/opt/central-ledger/src/domain/transfer/index.js:78:26)","apiErrorCode":{"code":"2001","message":"Internal server error","name":"INTERNAL_SERVER_ERROR","type":{"regex":"^20[0-9]{2}$","description":"Generic Server Error","name":"GENERIC_SERVER_ERROR"}},"useMessageAsDescription":false,"message":"Cannot read property 'insert' of undefined","stack":"FSPIOPError: Cannot read property 'insert' of undefinedn    at createFSPIOPError (/opt/central-ledger/node_modules/@mojaloop/central-services-error-handling/src/factory.js:201:12)n    at Object.reformatFSPIOPError (/opt/central-ledger/node_modules/@mojaloop/central-services-error-handling/src/factory.js:288:12)n    at Object.insert (/opt/central-ledger/src/models/transfer/transferError.js:54:32)n    at Object.logTransferError (/opt/central-ledger/src/domain/transfer/index.js:78:26)nTypeError: Cannot read property 'insert' of undefinedn    at Object.insert (/opt/central-ledger/src/models/transfer/transferError.js:52:29)n    at Object.logTransferError (/opt/central-ledger/src/domain/transfer/index.js:78:26)"}}}'
[backend-centralledger-handler-transfer-position-7ccc779c7brt2ll centralledger-handler-transfer-position-sidecar] 2019-11-06T16:26:32.864Z - info: Producer::end
[backend-centralledger-handler-transfer-position-7ccc779c7brt2ll centralledger-handler-transfer-position-sidecar] 2019-11-06T16:26:32.867Z - info: Received eventMessage:
[backend-centralledger-handler-transfer-position-7ccc779c7brt2ll centralledger-handler-transfer-position-sidecar] 2019-11-06T16:26:32.867Z - info: Producer.sendMessage::messageProtocol:'{"id":"32a3fe9d-8d88-426e-aecd-21d6613792f1","metadata":{"event":{"id":"3da82078-0c54-4d7d-bead-3dd5d837bf71","type":"trace","action":"span","createdAt":"2019-11-06T16:26:32.865Z","state":{"status":"failed","code":2001,"description":"Internal server error"}},"trace":{"service":"cl_transfer_position","traceId":"c558a42dc7eda0ed5da2f6c1562d51f2","spanId":"d44ddce887144dfe","parentSpanId":"8342569a3df9c4fc","startTimestamp":"2019-11-06T16:26:32.830Z","finishTimestamp":"2019-11-06T16:26:32.865Z","tags":{"transactionType":"transfer","transactionAction":"prepare","transactionId":"811af75a-3f98-4d13-8865-58c9387685fe","source":"payerfsp","destination":"payeefsp","payerFsp":"payerfsp","payeeFsp":"payeefsp"}}},"type":"application/json","content":{"payload":"Cannot read property 'insert' of undefined"}}'
[backend-centralledger-handler-transfer-position-7ccc779c7brt2ll centralledger-handler-transfer-position-sidecar] 2019-11-06T16:26:32.867Z - info: Producer::end
```

**Specifications**
  - Component (if known):  Central services
  - Version: 8.1.0
  - Platform: Mac OS
  - Subsystem: central ledger
  - Type of testing: Functional
  - Bug found/raised by: Sri

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by ggrg** [comment] 2019-11-06 17:07
I was not able to reproduce the issue locally. To me it seems to be something related to the migrations (as transferError table is missing) OR knex issue

**Comment by elnyry** [comment] 2019-11-08 08:17
@sri-miriyala @amarmodus please advise on if this can now be closed as the issue seems to have been resolved.

**Comment by amarmodus** [comment] 2019-11-08 12:12
<img width="1283" alt="Screenshot 2019-11-07 23 35 37" src="https://user-images.githubusercontent.com/53434415/68475776-f3c1e100-0220-11ea-8faf-a6718f5b6047.png">
Block transfer test cases are ok.

**Comment by elnyry** [comment] 2019-11-13 13:17
Waiting to hear about the status after moving to helm v8.4.0 - https://github.com/mojaloop/helm/releases/tag/v8.4.0

**Comment by amarmodus** [comment] 2019-11-14 14:47
![image](https://user-images.githubusercontent.com/53434415/68867272-777e4080-06ed-11ea-841e-080a9bdc7112.png)
![image](https://user-images.githubusercontent.com/53434415/68867381-a1376780-06ed-11ea-9133-1f957aaf7293.png)
Block transfer case and transfer negative scenarios - All pass in 8.4.0 deployment

**Comment by elnyry** [comment] 2019-11-14 19:29
Thanks @amarmodus closing this now

**Closed by elnyry** 2019-11-14 19:29 UTC
Labels: bug
