### ISSUE TITLE
Wrong error message displayed when you use incorrect expiration time format during the prepare 

### ISSUE THREAD

**Issue by bogere** [mojaloop/project#1053] opened 2019-11-08 20:01 UTC
**Summary**:
<Description regarding what the issue is (with important details) and where it is>

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry** [comment] 2019-11-09 02:38
Duplicate of #1054

**Closed by elnyry** 2019-11-09 02:38 UTC
Labels: duplicate
