### ISSUE TITLE
Killing the audit process allows auditable activities to be carried out without an audit trail being generated

### ISSUE THREAD

**Issue by PaulMakinMojaloop** [mojaloop/project#3914] opened 2024-05-15 13:47 UTC
**Summary**:
When running vNext, I found that if the audit BC process failed to start, or was directly terminated, I was able to carry out auditable activities (liquidity changes etc) with no entries being made in the audit log. This is a clear security/integrity risk; if an attacker is able to kill the audit process, they could (for example) allow a DFSP to continue transaction even if there is no liquidity available; come settlement time, this presents an existential risk to the scheme operator.

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**
If it is not possible to add an audit log entry, then the associated activity should not be allowed.

## Acceptance Criteria
 - [1 ] **Scenario: Audit process failure or termination prevents auditable activities**
  - Given the audit process fails or is terminated
  - When an auditable activity is attempted
  - Then the activity should not be allowed to proceed

**Comment by elnyry-sam-k** [comment] 2024-05-17 08:57
Thanks @PaulMakinMojaloop , this is critical. I've observed the same as well.

**Comment by PhyuSinMyat8** [comment] 2024-06-13 10:42
We have already tested the auditing service and discovered that once the auditing service has been restored, the actions that were performed during the downtime are recorded in the audit log.

Scenario 1
Step 1 : Terminate the auditing service
<img width="1399" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHhmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47a464d39a0ce882821aa2f8ba6299e51e3ed03a/image.png" alt="image.png" />
<img width="1426" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDFmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7bf01f1ba52e07524673e7753ef04d8fdcbc5565/image.png" alt="image.png" />

Step 2 : Deposit 1000 MXN to demoWalletLcc
<img width="1442" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDlmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3eca146655eb4971e009a016083763aac2708cfb/image.png" alt="image.png" />

Step 3 : Approve that fund deposit by user account
<img width="1263" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUJmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eea60b23e67ad7f69baf7c175e7c6ae85d86b7cb/image.png" alt="image.png" />

Result 1 : Any audit log is available since auditing service is down
<img width="1309" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUpmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8f7c279b928b4da0c0931128f7adb8cfa9d6b4c/image.png" alt="image.png" />

Step 5 : Auditing service is up
<img width="1387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU5mQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--278410aadbf7dc52e18242baaee0a795b48426f0/image.png" alt="image.png" />

Result 2 : Fund deposit and approval actions appear after the service has been up
<img width="1388" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVpmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96bd0849d44fa9772d951b9ce4e5a70fe4db3239/image.png" alt="image.png" />

Result 3 : Log details in kibana search
<img width="1644" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWRmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2fd2c43b75de3e84092b02378e5c1a03c91f9a5e/image.png" alt="image.png" />


Scenario 2
Step 1 : Terminate the auditing service
Step 2 : Make transactions
<img width="1319" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTlmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3255501ffbc5980e00efad3512f87b6cc38634ff/image.png" alt="image.png" />
<img width="1322" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkJmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--542013a444bbe0d5a14a8a174893999f88317a75/image.png" alt="image.png" />
<img width="1340" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkpmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca10f80ff0e340463dd048da8259da9c3f023711/image.png" alt="image.png" />

Step 3 : Auditing service is up
Result : These transactions appears in kibana after the service has been up 
<img width="1360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk5mQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba44323e3ab51912ee70b64a621468741002f918/image.png" alt="image.png" />

**Comment by TW-Ei-Nghon-Phoo** [comment] 2024-06-14 05:11
###Testing Result after termination of Kafka service

State 1: Kafka service is up.
<img width="800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0JqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e16ed50b9cb2be9150ffe6ed13776b392dc85738/image.png" alt="image.png" />
result 1: transaction is successful with 0 error. 
<img width="800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0pqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10b119b2e929081bd6ebe3053fc3a0767b8822a0/image.png" alt="image.png" />
State 2: Kakfa service is terminated.
<img width="800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK05qQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a7f683c8e7d843b2cac182b3b1854804dfc15cc/image.png" alt="image.png" />
Result 2: transaction is failed with 100% error rate. 
<img width="800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1ZqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93ad8941dcb651cb2374c27e3d9383ed9d54c066/image.png" alt="image.png" />
Result 3: No participant data available and no deposit activity available after Kafka service termination. 
<img width="1322" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1pqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51417f72e196cc5fd5820a441641dc57056c6c6f/image.png" alt="image.png" />

**Comment by Monicaminzy** [comment] 2024-06-14 09:42
test momo

**Comment by Monicaminzy** [comment] 2024-06-14 09:42
test momo

**Comment by JulieG19** [comment] 2024-06-19 10:11
Confirmed by @PaulMakinMojaloop that we can closed this comment.

**Closed by JulieG19** 2024-06-19 10:11 UTC
Labels: bug, vNext
