### ISSUE TITLE
POST /transfers with Accept: application/vnd.interoperability.transfers+json;version=1.0 gets a callback of version 1.1

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2054] opened 2021-02-16 07:29 UTC
**Summary**:
Using the testing toolkit, `p2p_happy_path.json` example (`/examples/dfsp/p2p_happy_path.json`), the `POST /transfers` test fails.

The `PUT /transfers/{id}` callback contains a `Content-Type` of  `application/vnd.interoperability.transfers+json;version=1.1`

**Severity**:

**Priority**:

**Expected Behavior**
I'm not 100% sure, but I think if the `Accept` header is set to `application/vnd.interoperability.transfers+json;version=1.0 ` 

**Steps to Reproduce**
  1. Follow the steps in this guide to set up a P2P transfer: http://beta.moja-lab.live/3-guides/5_ttk_p2p.html
  2. See that the transfer fails 1 test:

![ttk-bug-3](https://user-images.githubusercontent.com/1683980/108030667-86d20380-707f-11eb-860c-a56df46863c6.png)

  3. Inspect the logs and see that the `Content-Type` header is: `application/vnd.interoperability.transfers+json;version=1.1`

Output from TTK Monitoring for `PUT /transfers/{id}`
```json
{
  "request": {
    "uniqueId": "1613459926754nsnqgu",
    "headers": {
      "host": "eggmm-ttk-backend-fspiop.beta.moja-lab.live",
      "connection": "keep-alive",
      "x-forwarded-for": "10.42.3.0, 10.42.0.0",
      "x-forwarded-proto": "http",
      "x-forwarded-host": "eggmm-ttk-backend-fspiop.beta.moja-lab.live",
      "x-forwarded-port": "80",
      "x-forwarded-path": "/transfers/87c083a2-9577-408f-a719-8ef4af9305d6",
      "x-real-ip": "10.42.0.0",
      "content-length": "136",
      "content-type": "application/vnd.interoperability.transfers+json;version=1.1",
      "date": "Tue, 16 Feb 2021 07:18:46 GMT",
      "fspiop-source": "applebank",
      "fspiop-destination": "eggmm",
      "fspiop-http-method": "PUT",
      "fspiop-uri": "/transfers/87c083a2-9577-408f-a719-8ef4af9305d6",
      "fspiop-signature": "{\"signature\":\"AYcW6huzftQw3MDGOYlKVnluf1v_evJKtXr8eVhWBicb5jb7izXXZIFmX2jW4dw2tvR5uzaWhhdsmN-oNc_wLd-uIsQST5locWWDA8FQmbe25SUxNJjg7YG3_flWdk4EEJP4ozMRH8BO02iz8CmVVOWVYA-7cXO9HpfXTyK9dU879A-9iWl-avJV2Fo8dLPnqpBl8-z4h50ug0o5LG9hcO4_pcvYkAffdeJyxykNXeUeKtJD8qsU1nPZZbk-pWbVzYj3OKUTSsY4ooukF92ZAE2xvG1lVlggXegB2LWl_6FOIAWSTHg7sUA81ZCgr1beoRrKdmzpYOC0nYBsGAPWvQ\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzLzg3YzA4M2EyLTk1NzctNDA4Zi1hNzE5LThlZjRhZjkzMDVkNiIsIkZTUElPUC1IVFRQLU1ldGhvZCI6IlBVVCIsIkZTUElPUC1Tb3VyY2UiOiJhcHBsZWJhbmsiLCJGU1BJT1AtRGVzdGluYXRpb24iOiJlZ2dtbSIsIkRhdGUiOiJUdWUsIDE2IEZlYiAyMDIxIDA3OjE4OjQ2IEdNVCJ9\"}",
      "traceparent": "00-2833bff9def609669560ad0f1dc7fc20-27d3a170fd174b87-00",
      "tracestate": "mojaloop=eyJzcGFuSWQiOiIyN2QzYTE3MGZkMTc0Yjg3IiwidGltZUFwaUZ1bGZpbCI6IjE2MTM0NTk5MjY2ODAifQ==",
      "user-agent": "axios/0.20.0"
    },
    "queryParams": {},
    "body": {
      "completedTimestamp": "2021-02-16T07:18:46.672Z",
      "transferState": "COMMITTED",
      "fulfilment": "1vtO1ZbXqyAtqQOjlyv_taOQlV9d6_3ip-fJb5VhX-w"
    }
  }
}
```

**Specifications**
  - Component: `ml-api-adapter` 
  - Version:  `v11.1.2`
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Pull Requests**:
- [x] https://github.com/mojaloop/testing-toolkit-test-cases/pull/31

**Comment by mdebarros** [comment] 2021-02-19 11:03
PR currently open to address this bug --> https://github.com/mojaloop/postman/pull/199

**Comment by mdebarros** [comment] 2021-02-19 20:16
Fixed in release https://github.com/mojaloop/postman/releases/tag/v12.0.1.

@lewisdaly, could you verify on your side please?

**Comment by mdebarros** [comment] 2021-02-19 20:17
> PR currently open to address this bug in Postman collection --> [mojaloop/postman#199](https://github.com/mojaloop/postman/pull/199)

Fixed in release https://github.com/mojaloop/postman/releases/tag/v12.0.1.

@lewisdaly, could you verify on your side please?

**Comment by elnyry-sam-k** [comment] 2021-02-20 09:32
Guys @mdebarros , @lewisdaly - this is not a bug..

I resisted the temptation to respond to this earlier as I was taking a few days off :-).. Will discuss with you on Monday!

**Comment by elnyry-sam-k** [comment] 2021-02-20 10:35
For example, an FSP (a payee FSP) uses a version v1.1 of the FSPIOP API and another FSP (a payer FSP) uses a v1.0 of the FSPIOP API; Both are allowed to interact and transact since the major version is the same.. Its absolutely fine in principle for FSPs (or Switch for that matter) to transact while using the same major version of the FSPIOP API and a different minor version, since the minor version increments are backwards compatible...

**Comment by vijayg10** [comment] 2021-03-02 16:41
Created a followup story to extend this functionality
https://github.com/mojaloop/project/issues/2093

**Closed** 2021-03-02 16:42 UTC
Labels: bug, oss-ttk
