### ISSUE TITLE
Bulk- intermittent failures when processing 50 transfers

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2996] opened 2022-10-28 12:05 UTC
**Summary**:
I am facing intermittent failures (approx 3/10) when testing 50 transfers in a bulk transaction.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Observation**:

- The switch is sending 'Transfer Expired' to payer in PUT /bulkTransfers callbacks

**Comment by PaulGregoryBaker** [comment] 2022-11-07 10:20
Because of various other bug fixes, this is no-longer reproduceable. 

Closing issue.

**Closed by PaulGregoryBaker** 2022-11-07 10:20 UTC
Labels: bug, oss-bulk, core-dev-squad, ml-v14.1.0
